import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import Logo from "@/components/Logo";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                <Logo />
                {children}
                <Footer />
            </body>
        </html>
    );
}
